version: '3.4'

networks:
  app-tier:
    driver: bridge

services:
  crudcontainerization:
    image: crudcontainerization
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
